### ISSUE TITLE
Trouble running lme4 after updated R to 4.6.1 -  fixed by updating rlang (and Rcpp)

### ISSUE THREAD

**Issue by David-L-Duffy** [lme4/lme4#983]
After compiling and installing latest  R, lme4 would not load.

Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/home/R/lib/R/library/rlang/libs/rlang.so':
  /home/R/lib/R/library/rlang/libs/rlang.so: undefined symbol: SETLENGTH
Calls: <Anonymous> ... asNamespace -> loadNamespace -> library.dynam -> dyn.load

When I tried compiling the latest version of lme4, this failed with:
[...]
** this is package ‘lme4’ version ‘2.0-1’
[...]
/home/R/lib/R/library/Rcpp/include/Rcpp/Function.h: In constructor ‘Rcpp::Function_Impl<StoragePolicy>::Function_Impl(const std::string&, const std::string&)’:
/home/R/lib/R/library/Rcpp/include/Rcpp/Function.h:75:65: error: ‘R_NamespaceRegistry’ was not declared in this scope
   75 |             Shield<SEXP> env(R_getVarEx(Rf_install(ns.c_str()), R_NamespaceRegistry, FALSE, R_UnboundValue));
      |                                                                 ^~~~~~~~~~~~~~~~~~~

Googling, I find Dirk Eddelbeuttel retired R_NamespaceRegistry in April, saying this
is now R_getRegisteredNamespace(), and elsewhere comments this has affected production of a few debian packages. My version of 
Rcpp 1.1.1 was from January.

So, updating  Rcpp to 1.1.1-1.1, and rlang from existing 1.1.7 to 1.2.0 fixed the problems. That is, lme4 1.1-38 now worked, and lme4 2.0-1
successfully compiled and installed. 

Probably superfluous, but
C++ compiler: ‘g++ (Ubuntu 13.3.0-6ubuntu2~24.04.1) 13.3.0’
R version 4.6.1 (2026-06-24)
Platform: x86_64-pc-linux-gnu
Running under: Ubuntu 24.04.4 LTS

Matrix products: default
BLAS:   /home/R/lib/R/lib/libRblas.so 
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.12.0  LAPACK version 3.12.0

Cheers, David Duffy.

**Comment by bbolker** [comment]
> updating Rcpp to 1.1.1-1.1, and rlang from existing 1.1.7 to 1.2.0 fixed the problems.

in [DESCRIPTION](https://github.com/lme4/lme4/blob/master/DESCRIPTION) we currently only require Rcpp >= 0.10.5. It sounds like maybe we should update the requirement to >= 1.1.1-1.1 ?  Since Rcpp itself has no dependencies except R >= 3.5 (we already require >= 3.6), that seems harmless.

The `rlang` dependency was for a single convenience function; that functionality is now written internally, and the dependency is removed.

Thanks!
